export const HOME_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PROFILE_ROUTE = '/profile'
export const COLLECTION_ROUTE = '/collection'
export const ITEM_ROUTE = '/item'